// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmDk1Te121AkAUupX8TmwMJ2lOoTHm9g',
    appId: '1:610472142406:web:65d65dab04086a6d178c47',
    messagingSenderId: '610472142406',
    projectId: 'esavior-8f541',
    authDomain: 'esavior-8f541.firebaseapp.com',
    storageBucket: 'esavior-8f541.appspot.com',
    measurementId: 'G-0TP80JXWSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX4yoDNA9xEK0-SzYsLdn8zKx2gBrz9cQ',
    appId: '1:610472142406:android:45b87cf70f0a7b89178c47',
    messagingSenderId: '610472142406',
    projectId: 'esavior-8f541',
    storageBucket: 'esavior-8f541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmG13oLeIq7bfXKwtWD7Weu-qdXfZ6GHU',
    appId: '1:610472142406:ios:228767ed167f7d89178c47',
    messagingSenderId: '610472142406',
    projectId: 'esavior-8f541',
    storageBucket: 'esavior-8f541.appspot.com',
    iosBundleId: 'com.example.esaviourapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmG13oLeIq7bfXKwtWD7Weu-qdXfZ6GHU',
    appId: '1:610472142406:ios:228767ed167f7d89178c47',
    messagingSenderId: '610472142406',
    projectId: 'esavior-8f541',
    storageBucket: 'esavior-8f541.appspot.com',
    iosBundleId: 'com.example.esaviourapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApmDk1Te121AkAUupX8TmwMJ2lOoTHm9g',
    appId: '1:610472142406:web:84dc759ad2b53a61178c47',
    messagingSenderId: '610472142406',
    projectId: 'esavior-8f541',
    authDomain: 'esavior-8f541.firebaseapp.com',
    storageBucket: 'esavior-8f541.appspot.com',
    measurementId: 'G-XE2QJ8T3DJ',
  );
}
